### ISSUE TITLE
add text 1 and images 1 collections in pa.external-images.html

### ISSUE THREAD

**Issue by iuliia-iashchenko** [a34alefeliza/ile-pikimoni#3]
template: pa.external-images.html
new collections: text1, images1
interaction: drag&drop

add new collections to the template. Elements from these collections can be dragged and dropped on the external images.

**Comment by a34alefeliza** [comment]
you need a new exercise or shall I change the existing one?

**Comment by Dashkinru** [comment]
Please, change the existing one. Thank you!

**Comment by Dashkinru** [comment]
Alessandro, and is it possible to add a text here just to read it? Kind of, teachers find the picture to discuss, then a text and combine them for the ex. And then maybe we could also add text 2 to fill in the gaps in text 1?!

**Comment by Dashkinru** [comment]
Don't be mad at me if I'm typing nonsence))) I am again about this exercise... Cause I'm sure it's one of our strongest points - to give teachers the ability to use internet pictures and resources in one exercise with all possible options. 
So... Could you make something so that pictures from the same collection could be shown all at a time?
Besides, it would be great if sudents can, as Yulia and I have mentioned before, to put put prepared text collection on them. It would be a match exerces but with pictures from the Inet. 
Or... may be we could add these pictures to the Match exercise #10 to get our aim?

**Comment by a34alefeliza** [comment]
ok I am a bit lost... ))) can we meet and you will explain me.

**Comment by Dashkinru** [comment]
Yeah, we can meet))) But trying not to take your time, I'll make a video now. If I explain it not properly again, let me know)))
https://www.loom.com/share/65f23ef6ecab49bdaadd2886593e1197

**Comment by a34alefeliza** [comment]
Regarding image size: my point is that here you are using an image as a text. I guess you don't want to create a text collection out of it... what is the original size of that image? Can you send me the link?

Apart from the image size, would that be enough if I add the possibility to add external urls to the mixed collection? So that you can have a collection with internal images, text, audio, external images. And do you need this pa.external-images.html template? Or you want some other templates to use the mixed collection?

**Comment by Dashkinru** [comment]
1. Personally, I mostly see the usage of these urls like you saw in my example - text info from other books or webpage resourses. But I really don't want to create a text collection. 
https://www.loom.com/share/77ff715b67c64d4db95dabe05ab419e8
+ the link https://mcenglish.ru/wp-content/uploads/2017/09/verbs-followed-by-gerund-or-infinitive-grammar-drills-information-gap-activities_83903_3-724x1024.jpg
2. I've noticed that pretty often after clicking on ADD button nothing happens and!!! It's like you haven't done anything - espessially when it's about typing a text... The text vanishes...
video with the example
https://www.loom.com/share/ca096cd084d14e83a7aa580c806355ce
3. Out of 5 ADDs 2 aren't working: I don't see the text button and when I try to PLAY the video - there's a mistake. I've changed the links twice but it's the same every time.
![image](https://user-images.githubusercontent.com/66912801/103556586-12724500-4ec3-11eb-91af-d3dcb290b256.png)
4. "Apart from the image size, would that be enough if I add the possibility to add external urls to the mixed collection? So that you can have a collection with internal images, text, audio, external images. "
I see that you've already enlarged mixed collections)) That's awesome because this way we'll give teachers a wider range of combinations and oppotunity to fulfil their teacher's ambitions)))
5. "And do you need this pa.external-images.html template? Or you want some other templates to use the mixed collection?" 
I think let's leave it as it is. We need an ex to display images and sometimes people will mix these images with videos and something else.
