### ISSUE TITLE
New search box

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#48]
You might remember our conversation about creating a global search box (somewhere in the quick links sections) to look for any information on the platform no matter whether it is a collection or an exercise.

**Comment by a34alefeliza** [comment]
This is a very nice idea, very useful. But not now... new features like this one I need to postpone to... I dont know when, most likely September. I don't have much time to dedicate to Pikimoni right now. This is definitely a nice to have, but it is not a blocker. I will focus on blocker issues. Ok?

**Comment by Dashkinru** [comment]
Sure! No problem!

чт, 29 апр. 2021 г., 23:04 Alessandro ***@***.***>:

**Comment by a34alefeliza** [comment]
under Quick Links you have a new link, called Collections. Here you can search for any collection. On the search results you can click the gear icon and you get to the page where the collection is present, so that you can select it and use it.

![image](https://user-images.githubusercontent.com/9462653/120882658-7bc4c400-c5d9-11eb-8fc3-295db549f5f3.png)

**Comment by Dashkinru** [comment]
Great! I've already tried it:) So, a user can see their personal
collections and all admin collections in all levels available. It a level
isn't active they won't see anything from there, right?
С уважением,
Дарья


сб, 5 июн. 2021 г. в 09:39, Alessandro ***@***.***>:
