### ISSUE TITLE
Make the chosen collection more visible in saved workplans

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#74]
Hi! If it's OK with you, I'd like to suggest one more enhancement because for me it's a real trouble. Quite often, I need to change something in a collection that is already saved in a workplan and I can't clearly see the chosen collection when I'm scrolling through  a copious number of them.

https://www.loom.com/share/2e2d18d5bfec422b99526e52f0ab908e

**Comment by a34alefeliza** [comment]
Hi Dasha, yes I can do it. I was wondering: maybe I can do even better: In case of teacher's book and workplan, where collections are read-only and pre-selected (you cannot change collection) does it make sense to display all of them? What for? Maybe I can hide all collections but the selected one. I would display all of them only on Pages, where you can actually change the collection. Does it make sense?

**Comment by Dashkinru** [comment]
Hi! You know, I think it makes sense. Let's do it the way you suggest.
Thanks a lot!

вт, 31 янв. 2023 г., 00:59 Alessandro ***@***.***>:

**Comment by a34alefeliza** [comment]
after speaking to Yulia, I decided to go another way: the full list of collections is still there, but now the selected collection is always on top, so that you dont have to scroll the page:
<img width="489" alt="image" src="https://user-images.githubusercontent.com/9462653/216840987-c4b190c0-3e31-4219-8bb9-f195f3fd93eb.png">
