### ISSUE TITLE
HOMEWORK: questions 1. Archive

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#75]
I'm making a post about HW
I'm in doubt how to tell about the "Archive" button. Explain that people can use it to hide the exercises but in an emergency they can text us and we will restore the info? It sounds somehow lame...
Or maybe you will "activate" it? Make it completely functional? 
![image](https://user-images.githubusercontent.com/66912801/205611877-289b0d5f-792a-41d1-b8de-ff55286bdf68.png)

**Comment by a34alefeliza** [comment]
Hi, I think you can just say that with that button they can archive the homework once the it is no longer needed, so that it will no longer be visible. If we find out that it will be useful to see archived homework, then I can implement this feature in early 2023. I would NOT mention the possibility to contact support to restore an homework... this is alway possible but I would like to prevent any "abuse" of my very limited time :-) BTW I can add a confirmation popup ("Are you sure you want to archive this homework?") just to prevent mistakes.

**Comment by Dashkinru** [comment]
Ok. Get it. So mainly I have to say that for now "archive" is the synonym
for "remove". And pls add the confirmation you have mentioned. It'll be
safe this way.

пн, 5 дек. 2022 г., 13:47 Alessandro ***@***.***>:

**Comment by a34alefeliza** [comment]
the HW it's not really removed, I would say it's more a synonym for "hide from the this page".

Confirmation popup added.
